### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by YogliB** [testing-library/svelte-testing-library#38]
My test:
```javascript
import MyAwesomeComponent from '../src/components/MyAwesomeComponent.svelte';
import { render } from '@testing-library/svelte';

describe('MyAwesomeComponent', () => {
  test('should render greeting', () => {
    const { getByText } = render(MyAwesomeComponent, {
      props: { name: 'world' },
    });

    // eslint-disable-next-line jest/valid-expect
    expect(getByText('Hello world!'));
  });
});
```

My component:
```html
<script>
  export let name = 'stranger!';
</script>

<style>
  h1 {
    color: purple;
  }
</style>

<h1>Hello {name}</h1>
```

The error:
```bash
$ npm test

> svelte-component@ test D:\Projects\Svelte\svelte-component-template
> jest

 FAIL  tests/MyAwesomeComponent.spec.js
  ● Test suite failed to run

    D:\Projects\Svelte\svelte-component-template\tests\MyAwesomeComponent.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import MyAwesomeComponent from '../src/components/MyAwesomeComponent.svelte';
                                                                                                    ^^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.261s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by vborshchov** [comment]
same error

**Comment by vborshchov** [comment]
@YogliB Do you have babel.config.js file in your project with 
`
    module.exports = {
      presets: ["@babel/preset-env"]
    };
`?

**Comment by YogliB** [comment]
I have a `.babelrc`:
```json
{
  "include": [".js", ".mjs", ".html", ".svelte"],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    [
      "@babel/plugin-transform-runtime",
      {
        "useESModules": true
      }
    ]
  ],
  "presets": ["@babel/preset-env"],
  "ignore": ["node_modules/**"]
}

```

**Comment by YogliB** [comment]
@vborshchov Found the problem, `babel-jest` wasn't doing its job due to this line in my `.babelrc`:
```json
  "include": [".js", ".mjs", ".html", ".svelte"],
```
